### ISSUE TITLE
User's data collection by fake VASP providers?

### ISSUE THREAD

**Issue by Perlover** [uma-universal-money-address/protocol#8]
I have carefully studied your protocol. But I have an important question. How are you going to protect the transfer of user data (Travel Rule info) to fake servers that will impersonate a VASP provider? Example:

Alice is registered with a legal VASP provider vasp1.com and has an address `$alice@vasp1.com`. A certain Bob asked her to pay for some purchase and indicated his address: `$bob@vasp2.com`

Domain vasp2.com - running on Bob's personal server. [Bob generated the public and private key as described in your documentation](https://github.com/uma-universal-money-address/protocol/blob/main/umad-02-keys-and-authentication.md). The vasp2.com it works as it should, but its purpose is to collect personal data of users transmitted by the sender.

When Alice sends a payment to Bob, Bob's server receives Travel Rule info, which may include, as you yourself write (_For example, [IVMS](https://www.intervasp.org/#IVMS-1012023) is a standardized format for Travel Rule information, which is supported by many VASPs._), a large variety of data format: [full name, address, tax number, resident status, and so on](https://uploads-ssl.webflow.com/648841abc97f28489cc3f2ce/64c54ae23d8b1a5f16d13440_IVMS101.2023%20Working%20Draft%20For%20Consultation.pdf)

I have found no protection against this anywhere. What do you say to that?

**Comment by Perlover** [comment]
I can't even find an up-to-date list of VASP providers anywhere so that protection can be implemented at the whitelists level through domain filtering!

I didn't find anything even in the [FATF recommendations](https://www.fatf-gafi.org/content/dam/fatf-gafi/guidance/June2023-Targeted-Update-VA-VASP.pdf.coredownload.pdf) (maybe I searched badly)? How in general can one VASP distinguish another VASP from fake VASP?

It's scary to think if users' personal data will be transferred to attackers simply because some user decided to pay to some UMA address for something... These personal data can be collected, sold, they can be used by attackers in already outgoing transactions and thus "substitute" an innocent person.

**Comment by jklein24** [comment]
Closing out for tracking purposes, but please feel free to re-open if you still have questions on this. I'm happy to discuss further and talk through alternatives if you have more ideas.
